image: ubuntu

build:
  stage: build
  before_script:
    - apt update && apt -y install gcc make libboost-dev libyaml-cpp-dev
  script:
    - make noMEGAlib

pages:
  only:
    refs:
      - master
  stage: deploy
  script:
    - apt update && apt -y install make doxygen doxygen-doc doxygen-latex doxygen-gui libboost-dev libyaml-cpp-dev
    - git submodule update --init --recursive --remote
    - doxygen Doxyfile
  artifacts:
    paths:
      - public
